Fixes bug 28934:Error when launching "Create AP Expense Invoices".
The problem wasn't related with "Openbravo External Connection Pools module". This issue
has been reproduced without using "Apache JDBC Connection Pool", this is the error log:

Apr 27, 2015 12:51:47 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet P801268 threw exception
org.hibernate.TransactionException: JDBC commit failed
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:157)
	at org.openbravo.dal.core.SessionHandler.commitAndClose(SessionHandler.java:258)
.........................
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:701)
Caused by: org.postgresql.util.PSQLException: Cannot commit when autoCommit is enabled.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.commit(AbstractJdbc2Connection.java:705)
	at org.hibernate.transaction.JDBCTransaction.commitAndResetAutoCommit(JDBCTransaction.java:166)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:142)

In both cases (default connection pool or apache jdbc connection pool) there was an error
related with the way of manage connections in "Create AP Expense Invoices" process.

This connection is obtained with getConnection() method and finally it is closed in
realeaseCommitConnection() method. This method gets the connection from the session.
In following uses of "getConnection()" there is an error because this process closed
the connection of the session.

To fix this, using "getTransactionConnection()" instead of "getConnection()" method. This method
creates a new connection instead of using the connection of the session. For this reason, it can
be closed without any problem.

--HG--
extra : rebase_source : 2012043a1fe28a9b22ade6f13fc2ecfbca636934