fixed bug 31256: Lazy filtering does not work when filtering the first time
  Having lazy filtering configured, if a filter was applied in a grid as first
  action, it was not possible to apply it. A js error was thrown:
     Uncaught TypeError: this.data.willFetchData is not a function

  The problem was in "if (this.data.willFetchData(this.convertCriteria(criteria)))"
  statement which incorrectly assumed this.data to be an object and willFetchData
  a function within it. This is not true when in this situation where this.data is
  an array.

  It has been fixed by taking into account this case by checking wether this.data
  is an array.

--HG--
extra : rebase_source : cd0cc4ecd3377f8a1c8a95222e58e0d375c7f953