fixes bug 35654: module validation fails for killable BG processes using CDI
 The DatabaseValidator class uses Class.forName(className) to retrieve the class of the background processes and then determine if they implement the KillableProcess interface.

 When using that method, the class is also initialized. This initialization failed in some cases with a java.lang.NoClassDefFoundError if the class was making use of weld (CDI).

 As we don't need to initialize the background process class to determine if it implements the KillableProcess interface, we replace the usage of Class.forName(className) with Class.forName(className, false, classLoader). With the second argument the class initialization is prevented.