related to issue 38520: catch Throwable
  catch Throwable to avoid the failure of the export.database task which is throwing a NoClassDefFoundError when trying to recover the DalSessionFactoryController with weld

--HG--
extra : amend_source : e88a232b7afb38de9e6a08a564f1344cf7ef04b5