related to BUG-48994: disable test failing in JDK 22
  Disable tests temporarily because it fails when executing it with JDK
22 with the following error:

  org.mockito.exceptions.base.MockitoException: Mockito cannot mock this
class: interface javax.enterprise.inject.Instance